---
title: Comparing measures of central tendency
author: Joel Pick
output: html_document
---


```{r,echo=FALSE}

rm(list=ls())

library("beeswarm")

library(scales)
wd <- "~/github/bayes_perm/"

source(paste0(wd,"R/00_functions.R"))

files <- list.files(paste0(wd,"Data/Intermediate"))
results <- files[grep("gaus_sims",files)]
list_names <- gsub("gaus_sims_|.Rdata","",results)

## get all results into a list
# all <- list()
# for(i in 1:length(results)){
# 	load(paste0(wd,"Data/Intermediate/",results[i]))
# 	all[[list_names[i]]] <- out
# 	rm("out")
# }

actual<-as.data.frame(do.call(rbind,lapply(results, function(y){
	load(paste0(wd,"Data/Intermediate/",y))
	do.call(rbind,lapply(out, function(x){
	  z <- c(x$param,x$summary)
	  # ICC=x$ICC,N_group=x$N_group, N_within=x$N_within
	  names(z) <- c("pop","ICC","N_group","N_within","freq","mode0.1","mode1","median","mean","LCI","UCI","ESS")	
	  z
	}))
} )))

nrow(actual)

actual$mean_bias<-actual$mean-actual$ICC
actual$median_bias<-actual$median-actual$ICC
actual$mode1_bias<-actual$mode1-actual$ICC
actual$mode0.1_bias<-actual$mode0.1-actual$ICC

bias<-aggregate(cbind(mode0.1_bias,mode1_bias,mean_bias,median_bias)~ICC+N_group+N_within,actual,mean)
abs_bias<-aggregate(cbind(mode0.1_bias,mode1_bias,mean_bias,median_bias)~ICC+N_group+N_within,actual,function(x) mean(abs(x)))
rmse<-aggregate(cbind(mode0.1_bias,mode1_bias,mean_bias,median_bias)~ICC+N_group+N_within,actual,function(x) sqrt(mean(x^2)) )
# accuracy<-aggregate(cbind(mode0.1_bias,mode1_bias,mean_bias,median_bias)~ICC+N_group+N_within,actual,sd)
precision<-aggregate(cbind(mode0.1,mode1,mean,median)~ICC+N_group+N_within,actual,function(x)1/sd(x))
```


```{r,'estimate-plot', echo=FALSE, fig.height=10, fig.width=10}

agg <- aggregate(cbind(mean,median,mode1,mode0.1)~ICC+N_group+N_within,actual,mean)

line_coords <- (1:5)*4+0.5


{
par(mfrow=c(4,1), mar=c(0,4,4.5,0))
beeswarm(mean~ICC+N_group+N_within,actual, pch=19, cex=0.1, col=alpha(1,0.3),method = "compactswarm",corral="wrap",labels=rep(c(0,0.1,0.2,0.4)), ylab="Posterior Mean",  ylim=c(0,1))
# abline(h=0)
points(agg$mean, pch=19, col="blue")
points(agg$ICC, pch=19, col="red")

abline(v=line_coords, lty=c(2,2,1,2,2))
# axis(1,1:24,rep(c(0,0.1,0.2,0.4),6))
axis(3,(1:6) *4 -1.5,rep(c(20,40,80),2), tick=FALSE, line=-0.5)
axis(3,(1:3) *4 -1.5,c("",2,""), lwd.ticks=0, line=2, padj=1)
axis(3,(4:6) *4 -1.5,c("",4,""), lwd.ticks=0, line=2, padj=1)


par( mar=c(1.5,4,3,0))

beeswarm(median~ICC+N_group+N_within,actual, pch=19, cex=0.1, col=alpha(1,0.3),method = "compactswarm",corral="wrap",labels=rep(c(0,0.1,0.2,0.4)), ylab="Posterior Median",  ylim=c(0,1))
# abline(h=0)
points(agg$median, pch=19, col="blue")
points(agg$ICC, pch=19, col="red")
abline(v=line_coords, lty=c(2,2,1,2,2))

par( mar=c(3,4,1.5,0))

beeswarm(mode1~ICC+N_group+N_within,actual, pch=19, cex=0.1, col=alpha(1,0.3),method = "compactswarm",corral="wrap",labels=rep(c(0,0.1,0.2,0.4)), ylab="Posterior Mode (adjust=1)",  ylim=c(0,1))
# abline(h=0)
points(agg$mode1, pch=19, col="blue")
points(agg$ICC, pch=19, col="red")
abline(v=line_coords, lty=c(2,2,1,2,2))

par( mar=c(4.5,4,0,0))

beeswarm(mode0.1~ICC+N_group+N_within,actual, pch=19, cex=0.1, col=alpha(1,0.3),method = "compactswarm",corral="wrap",xlab="ICC", ylab="Posterior Mode (adjust=0.1",  ylim=c(0,1),labels=rep(c(0,0.1,0.2,0.4),3))
# abline(h=0)
points(agg$mode0.1, pch=19, col="blue")
points(agg$ICC, pch=19, col="red")
abline(v=line_coords, lty=c(2,2,1,2,2))

}
```

```{r,'bias-plot', echo=FALSE, fig.height=10, fig.width=10}

# line_coords <- (1:7)*3+0.5
	par(mfrow=c(4,1), mar=c(0,4,4.5,1))

plot(bias$mean_bias, pch=19, ylim=c(-0.2,0.2), ylab="Bias", xaxt="n")
abline(h=0)
abline(v=line_coords, lty=c(2,2,1,2,2))
# axis(1,1:24,rep(c(0,0.1,0.2,0.4),6))
axis(3,(1:6) *4 -1.5,rep(c(20,40,80),2), tick=FALSE, line=-0.5)
axis(3,(1:3) *4 -1.5,c("",2,""), lwd.ticks=0, line=2, padj=1)
axis(3,(4:6) *4 -1.5,c("",4,""), lwd.ticks=0, line=2, padj=1)

points(bias$median_bias, pch=19,col="red")
points(bias$mode1_bias, pch=19,col="blue")
points(bias$mode0.1_bias, pch=19,col="green")

legend("bottomleft",c("mean","median","mode-0.1","mode-1"), pch=19, col=c(1,2,3,4))

par(mar=c(1,4,2,1))
plot(abs_bias$mean_bias, pch=19, ylim=c(0,0.4), ylab="Absolute Bias", xaxt="n")
abline(h=0)
points(abs_bias$median_bias, pch=19,col="red")
points(abs_bias$mode1_bias, pch=19,col="blue")
points(abs_bias$mode0.1_bias, pch=19,col="green")
	abline(v=line_coords)
# axis(1,1:24,rep(c(0,0.1,0.2,0.4),6))

par(mar=c(2,4,1,1))
plot(rmse$mean_bias, pch=19, ylim=c(0,0.4), ylab="RMSE", xaxt="n")
abline(h=0)
points(rmse$median_bias, pch=19,col="red")
points(rmse$mode1_bias, pch=19,col="blue")
points(rmse$mode0.1_bias, pch=19,col="green")
	abline(v=line_coords)
# axis(1:24,rep(c(20,40,80,160),4))
# axis(1,1:24,rep(c(0,0.1,0.2,0.4),6))

par(mar=c(4,4,0,1))
plot(precision$mean, pch=19, ylim=c(0,100), ylab="Precision", xlab="ICC", xaxt="n")
abline(h=0)
points(precision$median, pch=19,col="red")
points(precision$mode1, pch=19,col="blue")
points(precision$mode0.1, pch=19,col="green")
	abline(v=line_coords)
axis(1,1:24,rep(c(0,0.1,0.2,0.4),6))

```

```{r,'bias-diff-plot', echo=FALSE, fig.height=8, fig.width=10}

# plot(bias$mean_bias-bias$median_bias);abline(h=0)
# plot(abs_bias$mean_bias-abs_bias$median_bias);abline(h=0)
# plot(rmse$mean_bias-rmse$median_bias);abline(h=0)
# plot(rmse$mode1_bias-rmse$median_bias);abline(h=0)
# plot(rmse$mode1_bias-rmse$mean_bias);abline(h=0)

# abs(actual$mean_bias) - abs(actual$median_bias)

bias_diff <- aggregate(cbind(
		mean.median=abs(mean_bias)-abs(median_bias),
		mode1.median=abs(mode1_bias)-abs(median_bias),
		mode1.mean=abs(mode1_bias)-abs(mean_bias),
		mode0.1.median=abs(mode0.1_bias)-abs(median_bias)
		)~ICC+N_group+N_within,actual,mean)

line_coords <- (1:5)*4+0.5
	par(mfrow=c(2,1), mar=c(1,4,4.5,1))
plot(bias_diff$mean.median, pch=19, col=1:4, ylim=range(bias_diff[,c(4:7)]), ylab="Abs Mean Bias - Abs Median Bias", xaxt="n"
	);
abline(h=0)
abline(v=line_coords, lty=c(2,2,1,2,2))
# axis(1,1:24,rep(c(0,0.1,0.2,0.4),6))
axis(3,(1:6) *4 -1.5,rep(c(20,40,80),2), tick=FALSE, line=-0.5)
axis(3,(1:3) *4 -1.5,c("",2,""), lwd.ticks=0, line=2, padj=1)
axis(3,(4:6) *4 -1.5,c("",4,""), lwd.ticks=0, line=2, padj=1)

par(mar=c(4.5,4,1,1))
plot(bias_diff$mode1.median, pch=19, col=1:4, ylim=range(bias_diff[,c(4:7)]), ylab="Abs Mode Bias - Abs Median Bias", xlab="ICC", xaxt="n"
	);abline(h=0)
abline(v=line_coords, lty=c(2,2,1,2,2))
axis(1,1:24,rep(c(0,0.1,0.2,0.4),6))

# points(bias_diff$mode0.1.median, pch=16, col=1:4, ylim=range(bias_diff[,c(4:6)]));abline(h=0)

# plot(aggregate(abs(mode1_bias)-abs(mean_bias)~N_group+N_within+ICC,actual,mean)[,4]);abline(h=0)
# plot(aggregate(abs(mode1_bias)-abs(mode0.1_bias)~N_group+N_within+ICC,actual,mean)[,4]);abline(h=0)



```



```{r, 'ess-plots', echo=FALSE, fig.height=6, fig.width=8}
## check ESS
par(mfrow=c(2,1))
 
hist(actual$ESS, breaks=100)
abline(v=500, col="red")
text(2000,600,paste0(round(sum(actual$ESS>500)/nrow(actual),3)*100,"% above 500"), cex=1.5)

boxplot(ESS~N_group+N_within+ICC,actual, las=2)
abline(h=500, col="red")

```


```{r, echo=FALSE}

###
# -- FIGURE 2
###


# actual <- as.data.frame(do.call(rbind,lapply(all, function(z){
# 	t(sapply(z, function(x) c(x$param,x$actual[1:6])))
# })))
# str(actual)
# boxplot(mean~N_within+N_group+ICC,actual,boxwex=0.5, pch=19, cex=0.5)
# head(actual)

# {
# 	# bias_plot0 <- subset(actual, ICC ==0 & N_group==40)[,1:9]
# 	bias_plot2 <- subset(actual, N_within ==4 & N_group==40)[,1:9]

# 	bp2_long<-Stack(bias_plot2, col2stack = c("freq","mean","mode1"),value.name = "estimate",group.name = "type")  
# 	bp0_long<-Stack(bias_plot0, col2stack = c("freq","mean","mode1"),value.name = "estimate",group.name = "type")

# 	par(mfrow=c(2,1), mar=c(5,5,2,1), cex.axis=0.75)
# 	# boxplot(estimate~N_within+type,bp2_long,boxwex=0.5,xlab="Within group sample size", names=rep(c(2,4,8),3), ylab="Estimate", pch=19, cex=0.5)
# 	beeswarm(estimate~N_within+type,bp2_long, pch=19, cex=0.5, col=alpha(1,0.3),method = "compactswarm",corral="wrap",xlab="Within group sample size", labels=rep(c(2,4,8),3), ylab="Estimate")
# 	means<-aggregate(estimate~N_within+type,bp2_long,mean)$estimate
# 	CIs<-aggregate(estimate~N_within+type,bp2_long,function(x) sd(x)/sqrt(length(x)))$estimate*qnorm(0.975)
# 	points(means, pch=19, cex=2, col="blue")
# 	arrows(1:9,means+CIs,1:9,means-CIs,code=0, angle=90, length=0.05, col="blue", lwd=2)
# 	abline(h=0.2, col="red", lwd=2)
# 	abline(v=c(3.5,6.5))
# 	mtext(c("ML","Posterior Mean","Posterior Mode"),side=3,adj=c(0.15,0.5, 0.85))

# 	# boxplot(estimate~N_within+type,bp0_long,boxwex=0.5,xlab="Within group sample size", ylab="Estimate", pch=19, cex=0.5, names=rep(c(2,4,8),3), ylim=c(0,0.3))#
# 	beeswarm(estimate~N_within+type,bp0_long, pch=19, cex=0.5, col=alpha(1,0.3),method = "compactswarm",corral="wrap",xlab="Within group sample size", labels=rep(c(2,4,8),3), ylab="Estimate")
# 	means<-aggregate(estimate~N_within+type,bp0_long,mean)$estimate
# 	CIs<-aggregate(estimate~N_within+type,bp0_long,function(x) sd(x)/sqrt(length(x)))$estimate*qnorm(0.975)
# 	points(means, pch=19, cex=2, col="blue")
# 	arrows(1:9,means+CIs,1:9,means-CIs,code=0, angle=90, length=0.05, col="blue", lwd=2)
# 	abline(h=0, col="red", lwd=2)
# 	abline(v=c(3.5,6.5))
# 	mtext(c("ML","Posterior Mean","Posterior Mode"),side=3,adj=c(0.15,0.5, 0.85))


# }
```

```{r, echo=FALSE}


	# bias_plot0 <- subset(actual, ICC ==0 & N_within==2)[,1:9]
	# bp0_long<-Stack(bias_plot0, col2stack = c("freq","mean","median","mode0.1","mode1"),value.name = "estimate",group.name = "type")

	# bias_plot2 <- subset(actual, ICC==0.2 & N_within==2)[,1:9]
	# bp2_long<-Stack(bias_plot2, col2stack = c("freq","mean","median","mode0.1","mode1"),value.name = "estimate",group.name = "type")

	# par(mfrow=c(2,1), mar=c(4,4,2,1), cex.axis=0.75, mgp=c(2,0.5,0))


	# # boxplot(estimate~N_group+type,bp0_long,boxwex=0.5,xlab="Number of Groups", ylab="Estimate", pch=19, cex=0.5, names=rep(c(20,40,80,160),3),  ylim=c(0,1))#
	# beeswarm(estimate~N_group+type,bp0_long, pch=19, cex=0.2, col=alpha(1,0.3),method = "compactswarm",corral="wrap",xlab="Number of Groups", labels=rep(c(20,40,80,160),3), ylab="Estimate",  ylim=c(0,1))
	# abline(h=0, col="red", lwd=2)
	# abline(v=c(4.5, 8.5, 12.5))
	# mtext(c("ML","Post. Mean","Post. Median","Post. Mode"),side=3,adj=c(0.12,0.375,0.625 ,0.9))
	# mtext("a)",2,padj=-12, las=1, line=2)
	# means<-aggregate(estimate~N_group+type,bp0_long,mean)$estimate
	# CIs<-aggregate(estimate~N_group+type,bp0_long,function(x) sd(x)/sqrt(length(x)))$estimate*qnorm(0.975)
	# points(means, pch=19, cex=1.5, col="blue")
	# arrows(1:16,means+CIs,1:16,means-CIs,code=0, angle=90, length=0.05, col="blue", lwd=2)

	# # boxplot(estimate~N_group+type,bp2_long,boxwex=0.5,xlab="Number of Groups",  ylab="Estimate", pch=19, cex=0.5, names=rep(c(20,40,80,160),3),  ylim=c(0,1))
	# beeswarm(estimate~N_group+type,bp2_long, pch=19, cex=0.2, col=alpha(1,0.3),method = "compactswarm",corral="wrap",xlab="Number of Groups", labels=rep(c(20,40,80,160),3), ylab="Estimate",  ylim=c(0,1))
	# abline(h=0.2, col="red", lwd=2)
	# abline(v=c(4.5, 8.5, 12.5))
	# mtext(c("ML","Post. Mean","Post. Median","Post. Mode"),side=3,adj=c(0.12,0.375,0.625 ,0.9))
	# mtext("b)",2,padj=-12, las=1, line=2)
	# means<-aggregate(estimate~N_group+type,bp2_long,mean)$estimate
	# CIs<-aggregate(estimate~N_group+type,bp2_long,function(x) sd(x)/sqrt(length(x)))$estimate*qnorm(0.975)
	# points(means, pch=19, cex=1.5, col="blue")
	# arrows(1:16,means+CIs,1:16,means-CIs,code=0, angle=90, length=0.05, col="blue", lwd=2)


```


```{r, echo=FALSE}
# bp0_long$bias<-abs(bp0_long$estimate - bp0_long$ICC)
# bp2_long$bias<-abs(bp2_long$estimate - bp2_long$ICC)

# {
# 	par(mfrow=c(2,1), mar=c(4,4,2,1), cex.axis=0.75, mgp=c(2,0.5,0))

# 	# boxplot(estimate~N_group+type,bp0_long,boxwex=0.5,xlab="Number of Groups", ylab="Estimate", pch=19, cex=0.5, names=rep(c(20,40,80,160),3),  ylim=c(0,1))#
# 	beeswarm(bias~N_group+type,bp0_long, pch=19, cex=0.5, col=alpha(1,0.3),method = "compactswarm",corral="wrap",xlab="Number of Groups", labels=rep(c(20,40,80,160),3), ylab="bias",  ylim=c(0,1))
# 	abline(h=0, col="red", lwd=2)
# 	abline(v=c(4.5, 8.5, 12.5))
# 	mtext(c("ML","Post. Mean","Post. Median","Post. Mode"),side=3,adj=c(0.12,0.375,0.625 ,0.9))
# 	mtext("a)",2,padj=-12, las=1, line=2)
# 	means<-aggregate(bias~N_group+type,bp0_long,mean)$bias
# 	CIs<-aggregate(bias~N_group+type,bp0_long,function(x) sd(x)/sqrt(length(x)))$bias*qnorm(0.975)
# 	points(means, pch=19, cex=1.5, col="blue")
# 	arrows(1:16,means+CIs,1:16,means-CIs,code=0, angle=90, length=0.05, col="blue", lwd=2)

# 	# boxplot(bias~N_group+type,bp2_long,boxwex=0.5,xlab="Number of Groups",  ylab="bias", pch=19, cex=0.5, names=rep(c(20,40,80,160),3),  ylim=c(0,1))
# 	beeswarm(bias~N_group+type,bp2_long, pch=19, cex=0.5, col=alpha(1,0.3),method = "compactswarm",corral="wrap",xlab="Number of Groups", labels=rep(c(20,40,80,160),3), ylab="bias",  ylim=c(0,1))
# 	abline(h=0, col="red", lwd=2)
# 	abline(v=c(4.5, 8.5, 12.5))
# 	mtext(c("ML","Post. Mean","Post. Median","Post. Mode"),side=3,adj=c(0.12,0.375,0.625 ,0.9))
# 	mtext("b)",2,padj=-12, las=1, line=2)
# 	means<-aggregate(bias~N_group+type,bp2_long,mean)$bias
# 	CIs<-aggregate(bias~N_group+type,bp2_long,function(x) sd(x)/sqrt(length(x)))$bias*qnorm(0.975)
# 	points(means, pch=19, cex=1.5, col="blue")
# 	arrows(1:16,means+CIs,1:16,means-CIs,code=0, angle=90, length=0.05, col="blue", lwd=2)
# }


```
